name: Build and Deploy IFC Viewer (GitHub Pages)

on:
  push:
    branches: ["main"]
    paths:
      - "ifc/**"
      - "viewer/**"
      - "scripts/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install ifcopenshell==0.8.4.post1

      - name: Download IfcConvert (IfcOpenShell)
        run: |
          mkdir -p tools
          cd tools
          curl -L -o ifcconvert.zip "https://github.com/IfcOpenShell/IfcOpenShell/releases/download/ifcconvert-0.8.4/ifcconvert-0.8.4-linux64.zip"
          unzip -o ifcconvert.zip
          chmod +x IfcConvert
          echo "${PWD}" >> $GITHUB_PATH

      - name: Build site
        run: |
          python scripts/build_site.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
